// This file was generated by Prisma and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import { join } from 'path';

// Load .env from root directory
import * as dotenv from 'dotenv';
import { defineConfig, env } from 'prisma/config';
dotenv.config({ path: join(__dirname, '../../.env') });

const mysqlUrl = `mysql://root:${env('MYSQL_ROOT_PASSWORD')}@${env('MYSQL_HOST')}:${env('MYSQL_PORT')}/${env('MYSQL_DATABASE')}`;

export default defineConfig({
  schema: 'prisma/schema',
  migrations: {
    path: 'prisma/migrations',
    seed: 'tsx prisma/seed.ts',
  },
  datasource: {
    url: mysqlUrl,
  },
});
